name: Build Cloudreve for MIPSel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-mipsle:
    runs-on: ubuntu-latest
    env:
      # 交叉编译目标
      GOOS: linux
      GOARCH: mipsle
      CGO_ENABLED: '0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'    # 可根据需要调整

      - name: Build Cloudreve binary
        run: |
          # 拉取依赖（如果使用 Go modules）
          go mod download

          # 编译带压缩符号表（减小体积）
          go build -ldflags="-s -w" -o cloudreve_mipsle ./main.go

          # 打印生成文件信息
          ls -lh cloudreve_mipsle

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudreve_linux_mipsle
          path: cloudreve_mipsle
