name: Build Cloudreve for MT7621

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip build-essential
        npm install -g yarn
        go install github.com/goreleaser/goreleaser@latest

    - name: Build Frontend
      run: |
        cd assets
        yarn install
        yarn build

    - name: Build Cloudreve
      env:
        GOOS: linux
        GOARCH: mipsle
        GOMIPS: softfloat
        CGO_ENABLED: 0
      run: |
        go mod tidy
        ~/go/bin/goreleaser build \
          --clean \
          --single-target \
          --snapshot \
          --id mt7621

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudreve-mt7621
        path: ./dist/cloudreve_*
