name: Build Cloudreve for MT7621

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Cloudreve
      env:
        GOOS: linux
        GOARCH: mipsle
        GOMIPS: softfloat
        CGO_ENABLED: 0
      run: |
        go build -v -o cloudreve -ldflags "-s -w" ./main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # 关键修改点：升级到 v4
      with:
        name: cloudreve-mt7621
        path: cloudreve
