name: Build Cloudreve for MT7621

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clean package locks
      run: rm -f package-lock.json  # 清除冲突的包锁定文件

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # 必须升级到 Node.js 20+

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip build-essential upx
        npm install -g yarn
        go install github.com/goreleaser/goreleaser@v1.19.2

    - name: Build Frontend
      run: |
        cd assets
        yarn install --ignore-engines  # 强制安装忽略版本检查
        yarn build

    - name: Build Cloudreve
      env:
        GOOS: linux
        GOARCH: mipsle
        GOMIPS: softfloat
        CGO_ENABLED: 0
      run: |
        go mod tidy
        ~/go/bin/goreleaser build \
          --clean \
          --single-target \
          --snapshot \
          --id mt7621 \
          -a mipsle \
          --ldflags "-s -w"

    - name: UPX compress
      run: |
        upx --best ./dist/cloudreve_*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudreve-mt7621
        path: ./dist/cloudreve_*