name: Build Cloudreve for MT7621

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 关键点1：获取子模块

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Build Frontend
      run: |  # 关键点2：构建前端资源
        cd cloudreve/frontend
        npm install
        npm run build
        cd ../ && zip -r assets.zip frontend/dist/*

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Cloudreve
      env:
        GOOS: linux
        GOARCH: mipsle
        GOMIPS: softfloat
        CGO_ENABLED: 0
      run: |
        go build -v -o cloudreve -ldflags "-s -w" ./main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cloudreve-mt7621
        path: cloudreve
