name: Build Cloudreve for MT7621

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip build-essential file
        go install github.com/goreleaser/goreleaser@v1.19.2

    - name: Configure GoReleaser
      run: |
        cat <<EOF > .goreleaser.yaml
        builds:
          - id: mt7621
            binary: cloudreve
            no_unique_dist_dir: true
            env:
              - CGO_ENABLED=0
              - GOARCH=mips
              - GOOS=linux
              - GOMIPS=softfloat
            flags:
              - -trimpath
            ldflags:
              - -s -w
            goos:
              - linux
            goarch:
              - mips
            gomips:
              - softfloat
        EOF

    - name: Print GoReleaser Config
      run: |
        echo "以下是 .goreleaser.yaml 的内容："
        cat .goreleaser.yaml

    - name: Verify Go Environment
      run: |
        echo "以下是 Go 环境变量："
        go env
        echo "GOARCH=$GOARCH"
        echo "GOOS=$GOOS"

    - name: Build Cloudreve
      run: |
        go mod tidy
        ~/go/bin/goreleaser build \
          --clean \
          --single-target \
          --snapshot \
          --id mt7621

    - name: Verify Binary
      run: |
        echo "以下是生成二进制文件的信息："
        file dist/cloudreve
        ls -lh dist/cloudreve
